-- CREATE TABLE FROM LOCAL CSV
-- CREATE A SNOWFLAKE FILE FORMAT, STAGE & PUT LOCAL LOCATION TO STAGE, TABLE, COPY DATA FROM STAGE

CREATE FILE FORMAT CSV_FILE 
			TYPE = CSV
			SKIP_HEADER = 1
			EMPTY_FIELD_AS_NULL = TRUE
			SKIP_BLANK_LINES = TRUE
			NULL_IF = ('\\N', 'NULL', 'NUL', '', '""')
;



CREATE STAGE DATA_STAGE_CUSTOMERS_CURRENT
     FILE_FORMAT = CSV_FILE	
;

CREATE STAGE DATA_STAGE_CUSTOMERS_UPDATES
     FILE_FORMAT = CSV_FILE	
;


PUT file:////Users/matthias/Data/customers_current.csv @DATA_STAGE_CUSTOMERS_CURRENT
;

PUT file:////Users/matthias/Data/customers_updates.csv @DATA_STAGE_CUSTOMERS_UPDATES
;


CREATE TABLE PUBLIC.CUSTOMERS_CURRENT (
    CUSTOMER_ID SMALLINT, 
    UPDATE_DATE VARCHAR(16),
    LOCATION VARCHAR(64)
    )
;

CREATE TABLE PUBLIC.CUSTOMERS_UPDATES (
    CUSTOMER_ID SMALLINT, 
    UPDATE_DATE VARCHAR(16),
    LOCATION VARCHAR(64),
    UPDATE_FLAG VARCHAR(2) 
    )
;



COPY INTO PUBLIC.CUSTOMERS_CURRENT FROM @DATA_STAGE_CUSTOMERS_CURRENT
;

COPY INTO PUBLIC.CUSTOMERS_UPDATES FROM @DATA_STAGE_CUSTOMERS_UPDATES
;

